Upgrade to Genesis v2.7.0
Updates to work correctly with Genesis v2.7.0.  This also fixes issue #9
by removing the domain check and relying on Gensis to validate the CN,
which is now supported in v2.7.0.

diff --git a/hooks/check b/hooks/check
--- a/hooks/check
+++ b/hooks/check
@@ -1,39 +1,14 @@
 #!/bin/bash
 
 # Cloud Config checks
-ok=yes
 if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
-    cloud_config_needs vm_type    $(lookup params.vm_type    default)
-    cloud_config_needs network    $(lookup params.network    minio)
-    cloud_config_needs disk_type  $(lookup params.disk_type  minio)
-    if check_cloud_config ; then
-      describe "  cloud-config [#G{OK}]"
-    else
-      ok=no
-    fi
-fi
-
-vault="secret/$GENESIS_VAULT_PREFIX"
-domain="minio.$(lookup params.network minio).$(lookup params.env)-minio.bosh"
-for cert in ssl/server; do
-  if ! safe exists "$vault/$cert"; then
-    describe "  ❌  $vault/$cert [#Y{MISSING}]"
-    ok=no
+  cloud_config_needs vm_type    "$(lookup params.vm_type    default)"
+  cloud_config_needs network    "$(lookup params.network    minio)"
+  cloud_config_needs disk_type  "$(lookup params.disk_type  minio)"
+  if check_cloud_config ; then
+    describe "  cloud-config [#G{OK}]"
   else
-    if safe --quiet x509 validate "$vault/$cert" --for "*.$domain" >/dev/null 2>&1; then
-      describe "  #G{✔}  $vault/$cert [#G{OK}]"
-    else
-      describe "  ❌  $vault/$cert [#R{INVALID}]"
-      safe x509 validate "$vault/$cert" --for "*.$domain" 2>&1 | sed -e 's/^/      /';
-      ok=no
-      echo
-    fi
+    describe "  cloud-config [#G{FAILED}]"
+    exit 1
   fi
-done;
-
-if [[ "$ok" = "yes" ]]; then
-  describe "  environment files [#G{OK}]"
-else
-  describe "  environment files [#R{FAILED}]"
-  exit 1
 fi
